
GET http://localhost:8888/api/autosearch?keyword=par&pageLimit=5&pageOffset=0

###Search hotels by city code and booking parameters
GET http://localhost:8888/api/city-hotels/?cityCode=LON&checkInDate=2022-05-29&checkOutDate=2022-05-30&adults=1&priceRange=200-300&pageLimit=3
###
//search hotels by name
GET http://localhost:8888/api/city-hotelsByname/?hotelName=AMBA

### Search hotels by ID
GET http://localhost:8888/api/hotel-offers?hotelId=EDLONDER&checkInDate=2022-05-29&checkOutDate=2022-05-30&adults=2

###
GET http://localhost:8888/api/hotel-offer?offerId=RHWD73YKQV

###
GET http://localhost:8888/api/search-location?keyword=par&pageLimit=5&pageOffset=0

###
GET http://localhost:8888/api/autosuggest

######## FLIGHT SEARCH

GET http://localhost:8888/api/flightsearch

